spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #关闭模板引擎的缓存
  thymeleaf:
    cache: false

#server:
#  port: 8888


#整合mybatis
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
#  映射器
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    类型别名
  type-aliases-package: com.milotnt.pojo


#关闭模板引擎的缓存